### ISSUE TITLE
ProvePossession -- challenge index generation

### ISSUE THREAD

**Issue by ZenGround0** [FILCAT/pdp#9]
1. Determine the correct randomness to draw from based on challenge period and latest proof of possession
2. Sample randomness from evm GetRandDAO opcode 
3. Use randomness to get challenge index

**Comment by anorth** [comment]
In my design sketch for this, randomness comes from drand v2 and does not depend on the chain environment at all.

Perhaps there's some reason that drand can't be used, like very slow verification inside EVM? RandDao is probably ok in that case, but I worry it limits portability. Does Filecoin implement that call in terms of drand beacons in the block header?

**Comment by anorth** [comment]
As it stands today, we can't verify drand beacons inside FEVM because we don't have precompiles for the underlying pairing operations.

We also can't use the EVM PREVRANDAO opcode to achieve exactly what we want because it only exposes randomness from the previous block header. We want the randomness to look back to an epoch locked in earlier. Using only the previous block would also require providers to compute their proof and get it included on chain in the space of one epoch. This isn't unreasonable usually, but additional stress and breathless.

Two potential paths forward:
- There's [existing discussion](https://github.com/filecoin-project/FIPs/discussions/846) about adding BLS opcodes to the FEVM, and these could hopefully mirror those we expect to [land in Ethereum](https://eips.ethereum.org/EIPS/eip-2537). If we can get a FIP for these through quickly, it might not block eventual release here.
- If we can't get the BLS opcodes, then we could ship a first version that uses PREVRANDAO, with all its drawbacks, in order to ship something and be able to build on top of it, and then ship a new version later that uses drand.

**Comment by anorth** [comment]
See #44 for using proper randomness, but the remaining challenge index generation is done in #41.
